#!/usr/bin/env bash
echo "Running detekt check..."
OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detekt detektDebug > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT

echo "Running lint check..."
LINT_OUTPUT="/tmp/lint-$(date +%s)"
./gradlew lint > "$LINT_OUTPUT"
LINT_EXIT_CODE=$?
if [ $LINT_EXIT_CODE -ne 0 ]; then
  cat "$LINT_OUTPUT"
  rm "$LINT_OUTPUT"
  echo "***********************************************"
  echo "                  lint failed                  "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $LINT_EXIT_CODE
fi
rm "$LINT_OUTPUT"
