name: Android CI

on:
  workflow_run:
    workflows: [ "Pre-build" ]
    types:
      - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug

  lint:
    needs: [ build ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Lint
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lintDebug

  test:
    needs: [ build ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Unit tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: testDebugUnitTest --info
      - name: Android Test Report Action
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() && runner.os == 'Linux' }}
      - name: Konsist tests
        run: ./gradlew :konsist:test
