name: Auto-label AI-Describe

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add "ai-describe" label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ai-describe
