name: CI Workflows

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  detekt:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Detekt
        uses: gradle/gradle-build-action@v3
        with:
          arguments: detekt detektDebug

  build:
    runs-on: macos-latest
    needs: detekt

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug

  lint:
    runs-on: macos-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Lint
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lintDebug

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Run Unit and Instrumented Tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean testDebugUnitTest --info

      - name: Find and Upload All Debug Test Reports
        if: ${{ always() }}
        run: |
          find . -type d -path "*/build/reports/tests/testDebugUnitTest" -exec echo "Found report at {}" \;
          find . -type d -path "*/build/reports/tests/testDebugUnitTest" -exec zip -r debug-test-reports.zip {} +
        uses: actions/upload-artifact@v3
        with:
          name: debug-test-reports
          path: debug-test-reports.zip
