name: iOS CI

on:
  workflow_run:
    workflows: [ "Pre-build" ]
    types:
      - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: linkIosArm64 iosArm64MainBinaries

  build-simulator:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup_gradle

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: linkIosSimulatorArm64 iosSimulatorArm64MainBinaries
